In [1]:
# Import Libraries

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [5]:
df=pd.read_csv('movie_metadata.csv')
df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [9]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

### 2. Use crosstabs to show the number of moovies per country

In [12]:
pd.crosstab(df.country,df.movie_title)

movie_title,#Horror,10 Cloverfield Lane,10 Days in a Madhouse,10 Things I Hate About You,102 Dalmatians,10th & Wolf,11:14,12 Angry Men,12 Monkeys,12 Rounds,...,Zoolander 2,Zoolander,Zoom,Zulu,[Rec] 2,[Rec],eXistenZ,xXx: State of the Union,xXx,Æon Flux
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aruba,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bahamas,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turkey,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
UK,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
USA,1,1,1,1,1,1,1,1,1,1,...,1,0,1,0,0,0,0,1,1,1
United Arab Emirates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
West Germany,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df1 = pd.crosstab(df.country, df.movie_title,margins=True, margins_name="Total").reset_index()
df1[['country','Total']]

movie_title               country  Total
0                     Afghanistan      1
1                       Argentina      4
2                           Aruba      1
3                       Australia     55
4                         Bahamas      1
..                            ...    ...
61                             UK    448
62                            USA   3807
63           United Arab Emirates      1
64                   West Germany      3
65                          Total   5038

[66 rows x 2 columns]

In [33]:
df1=pd.crosstab(df['country'], df['color'], margins=True).All
df1

country
Afghanistan                1
Argentina                  4
Aruba                      1
Australia                 55
Bahamas                    1
                        ...
UK                       447
USA                     3793
United Arab Emirates       1
West Germany               3
All                     5021
Name: All, Length: 66, dtype: int64

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [37]:
pd.crosstab([df['director_name'], df['genres']], df['country'])

,country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
director_name,genres,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Action|Adventure|Comedy|Fantasy|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Hann,Drama|Horror|Mystery|Sci-Fi|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Schneider,Drama|Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Seltzer,Comedy|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Abel Ferrara,Crime|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,Comedy|Music|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Álex de la Iglesia,Crime|Mystery|Thriller,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Émile Gaudreault,Comedy|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Éric Tessier,Action|Drama|Horror|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Étienne Faure,Drama|Musical|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 4. Average duration of filmes grouped by color

In [46]:
pd.crosstab(df.color,df.color,values=df.duration, aggfunc='mean').round(0)

color              Black and White  Color
color
 Black and White             112.0    NaN
Color                          NaN  107.0

In [42]:
df.groupby('color')['duration'].mean()

color
 Black and White    112.253589
Color               107.042908
Name: duration, dtype: float64

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [49]:
df['like'] = df['actor_3_facebook_likes']+df['actor_1_facebook_likes']+df['actor_2_facebook_likes']
df.groupby('director_name')['like'].mean()

director_name
A. Raven Cruz          1094.0
Aaron Hann              406.0
Aaron Schneider       16970.0
Aaron Seltzer          4598.0
Abel Ferrara           2198.0
                       ...
Zoran Lisinac           870.0
Álex de la Iglesia      702.0
Émile Gaudreault        917.0
Éric Tessier             72.0
Étienne Faure            19.0
Name: like, Length: 2398, dtype: float64